#!/bin/bash
printf "###########################################################\n"
printf "|apt-get install [package]|パッケージのインストール/更新|\n"
printf "|apt-get update           |パッケージリストの更新|\n"
printf "|apt-get upgrade          |インストールされてるパッケージの更新|\n"
printf "|apt-get dist-upgrade     |インストールされてるカーネルの更新(Ubuntu)/ディストリビューションの更新(Debian)|\n"
printf "|dpkg -l [package]        |インストールされてるパッケージの一覧|\n"
printf "|dpkg -L                  |インストールした時のファイルの一覧|\n"
printf "|apt-cache search [query] |パッケージの検索|\n"
printf "|apt-cache policy [query] |パッケージの検索 (インストール可能なバージョンの表示）|\n"
printf "|apt-cache madison [query]|パッケージの検索 (インストール可能なバージョンの一覧）|\n"
printf "|apt-get remove [package] |パッケージの削除|\n"
printf "|apt-get autoremove       |使ってないパッケージの削除|\n"
printf "|apt-get purge [package]  |パッケージの削除（設定ファイルも）|\n"
printf "|apt-get clean            |アーカイブファイルの削除|\n"
printf "|apt-get autoclean        |使ってないパッケージのアーカイブファイルの削除|\n"
printf "###########################################################\n"
